# Dependabot configuration for AI Scientist v2
# Automated dependency updates and security patches

version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "maintainer-team"
    assignees:
      - "maintainer-team"
    commit-message:
      prefix: "⬆️ deps"
      prefix-development: "⬆️ dev-deps"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    # Security updates
    allow:
      - dependency-type: "all"
    # Group minor and patch updates
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 3
    reviewers:
      - "maintainer-team"
    commit-message:
      prefix: "⬆️ actions"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"

  # Docker (if we add Dockerfile later)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "⬆️ docker"
      include: "scope"
    labels:
      - "docker"
      - "automated"