apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-scientist
  namespace: ai-scientist
spec:
  template:
    spec:
      containers:
      - name: ai-scientist
        resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"
            nvidia.com/gpu: "1"
          limits:
            memory: "16Gi"
            cpu: "8000m"
            nvidia.com/gpu: "2"
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        - name: WORKER_PROCESSES
          value: "8"
        - name: MAX_CONCURRENT_EXPERIMENTS
          value: "5"
        - name: CACHE_TTL
          value: "7200"
        - name: COST_TRACKING_ENABLED
          value: "true"
        - name: PROMETHEUS_METRICS_ENABLED
          value: "true"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-scientist-redis
  namespace: ai-scientist
spec:
  template:
    spec:
      containers:
      - name: redis
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"