# Pre-commit configuration for AI Scientist v2
# Install with: pip install pre-commit && pre-commit install

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]  # Allow custom YAML tags in config files
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: debug-statements
      - id: check-case-conflict
      - id: check-docstring-first
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=100]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black, --line-length=100]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=100, --ignore=E203,W503,F401]
        additional_dependencies: [flake8-docstrings]

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [-r, -x, tests/]
        exclude: ^tests/

  - repo: local
    hooks:
      - id: security-check-os-popen
        name: Check for os.popen usage (security)
        entry: bash -c 'if grep -r "os\.popen" ai_scientist/; then echo "Security violation: os.popen found!"; exit 1; fi'
        language: system
        files: \.py$
        
      - id: security-check-eval-exec
        name: Check for eval/exec usage (security)
        entry: bash -c 'if grep -r -E "(^|[^a-zA-Z_])eval\s*\(|(^|[^a-zA-Z_])exec\s*\(" ai_scientist/; then echo "Security warning: eval/exec found - ensure this is in security validation code only"; fi'
        language: system
        files: \.py$
        always_run: false
        
      - id: test-security-features
        name: Test security validation system
        entry: python tests/test_security_validation_simple.py
        language: system
        files: (ai_scientist/utils/code_security\.py|ai_scientist/treesearch/interpreter\.py)
        pass_filenames: false
        
      - id: test-error-handling
        name: Test enhanced error handling
        entry: python tests/test_enhanced_error_handling.py
        language: system
        files: ai_scientist/treesearch/(error_handling|parallel_agent)\.py
        pass_filenames: false
        
      - id: validate-config-files
        name: Validate configuration files
        entry: python -c "import yaml; yaml.safe_load(open('bfts_config.yaml', 'r'))"
        language: system
        files: .*\.ya?ml$
        pass_filenames: false

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --no-strict-optional]
        additional_dependencies: [types-PyYAML, types-requests]
        exclude: ^tests/

# Configuration for specific tools
default_stages: [commit]
fail_fast: false

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks
    
    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false