apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-scientist-data
  namespace: ai-scientist
  labels:
    app.kubernetes.io/name: ai-scientist
    app.kubernetes.io/version: v2.0.0
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: ai-scientist-platform
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: fast-ssd
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-scientist-logs
  namespace: ai-scientist
  labels:
    app.kubernetes.io/name: ai-scientist
    app.kubernetes.io/version: v2.0.0
    app.kubernetes.io/component: logs
    app.kubernetes.io/part-of: ai-scientist-platform
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-scientist-redis-data
  namespace: ai-scientist
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 7.0
    app.kubernetes.io/component: cache-storage
    app.kubernetes.io/part-of: ai-scientist-platform
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: fast-ssd
  volumeMode: Filesystem