apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-scientist
  namespace: ai-scientist
  labels:
    app.kubernetes.io/name: ai-scientist
    app.kubernetes.io/version: v2.0.0
    app.kubernetes.io/component: service-account
    app.kubernetes.io/part-of: ai-scientist-platform
  annotations:
    kubernetes.io/service-account.name: ai-scientist

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ai-scientist-role
  namespace: ai-scientist
  labels:
    app.kubernetes.io/name: ai-scientist
    app.kubernetes.io/version: v2.0.0
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: ai-scientist-platform
rules:
# ConfigMaps and Secrets (read-only)
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
# Pods (read-only for health checks and debugging)
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
# Services (read-only)
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
# PersistentVolumeClaims (read-only)
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
# Events (create for logging)
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ai-scientist-binding
  namespace: ai-scientist
  labels:
    app.kubernetes.io/name: ai-scientist
    app.kubernetes.io/version: v2.0.0
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: ai-scientist-platform
subjects:
- kind: ServiceAccount
  name: ai-scientist
  namespace: ai-scientist
roleRef:
  kind: Role
  name: ai-scientist-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ai-scientist-metrics-reader
  labels:
    app.kubernetes.io/name: ai-scientist
    app.kubernetes.io/version: v2.0.0
    app.kubernetes.io/component: cluster-rbac
    app.kubernetes.io/part-of: ai-scientist-platform
rules:
# Node metrics (for cost optimization)
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
# Metrics API
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ai-scientist-metrics-binding
  labels:
    app.kubernetes.io/name: ai-scientist
    app.kubernetes.io/version: v2.0.0
    app.kubernetes.io/component: cluster-rbac
    app.kubernetes.io/part-of: ai-scientist-platform
subjects:
- kind: ServiceAccount
  name: ai-scientist
  namespace: ai-scientist
roleRef:
  kind: ClusterRole
  name: ai-scientist-metrics-reader
  apiGroup: rbac.authorization.k8s.io