name: Security Vulnerability
description: Report a security vulnerability (private disclosure)
title: "[SECURITY] "
labels: ["security", "critical", "needs-immediate-attention"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT**: If this is a critical security vulnerability, please consider reporting it privately first.
        
        For responsible disclosure, contact the maintainers directly before creating a public issue.

  - type: dropdown
    id: severity
    attributes:
      label: Security Severity
      description: How severe is this vulnerability?
      options:
        - Critical (Remote code execution, full system compromise)
        - High (Privilege escalation, significant data exposure)
        - Medium (Limited access, minor data exposure)
        - Low (Information disclosure, denial of service)
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Vulnerability Category
      description: What type of security issue is this?
      options:
        - Code Injection/Execution
        - Path Traversal
        - Insecure File Operations
        - API Key/Secret Exposure
        - Input Validation Bypass
        - Authentication/Authorization
        - Dependency Vulnerability
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: A detailed description of the security vulnerability
      placeholder: Describe the vulnerability, its impact, and potential attack vectors.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Proof of Concept
      description: Steps to reproduce or proof of concept (remove any actual exploitation code)
      placeholder: |
        1. Specific steps to demonstrate the vulnerability
        2. Expected vs actual security behavior
        3. Any specific conditions required
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: What are the potential consequences of this vulnerability?
      placeholder: |
        - What can an attacker accomplish?
        - What data/systems are at risk?
        - What privileges could be gained?
    validations:
      required: true

  - type: textarea
    id: affected
    attributes:
      label: Affected Components
      description: Which parts of the system are affected?
      placeholder: |
        - Specific files/modules
        - Versions affected
        - Configuration scenarios
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: If you have suggestions for fixing this vulnerability
      placeholder: Potential fixes, workarounds, or mitigation strategies

  - type: checkboxes
    id: disclosure
    attributes:
      label: Responsible Disclosure
      description: Disclosure preferences
      options:
        - label: I have attempted to contact maintainers privately first
        - label: This issue can be disclosed publicly immediately
        - label: I request coordinated disclosure with a timeline
        - label: I am willing to help test the fix

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Environment where vulnerability was discovered
      value: |
        - OS: 
        - Python version: 
        - AI Scientist version/commit: 
        - Execution context (local/container/cloud):
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **Note**: Security vulnerabilities will be prioritized and handled according to our security policy.
        Critical vulnerabilities will be addressed immediately.