apiVersion: v1
kind: Namespace
metadata:
  name: ai-scientist
  labels:
    name: ai-scientist
    app.kubernetes.io/name: ai-scientist
    app.kubernetes.io/part-of: ai-scientist-platform
    app.kubernetes.io/managed-by: kubectl
    environment: production
  annotations:
    description: "AI Scientist v2 autonomous SDLC platform namespace"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ai-scientist-quota
  namespace: ai-scientist
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    requests.nvidia.com/gpu: "10"
    limits.cpu: "40"
    limits.memory: 80Gi
    limits.nvidia.com/gpu: "10"
    persistentvolumeclaims: "20"
    pods: "50"
    services: "20"
    secrets: "30"
    configmaps: "30"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: ai-scientist-limits
  namespace: ai-scientist
spec:
  limits:
  - type: Container
    default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "500m"
      memory: "1Gi"
    max:
      cpu: "8"
      memory: "16Gi"
      nvidia.com/gpu: "2"
    min:
      cpu: "100m"
      memory: "256Mi"
  - type: PersistentVolumeClaim
    max:
      storage: "1Ti"
    min:
      storage: "1Gi"